mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
  ports:
    - "3336:3306"
  volumes:
    - ./:/dev-env


dwstream:
  build: ../memex-datawake-stream
  links:
    - mysql:mysql
  environment:
      DW_DB: datawake_prefetch
      DW_DB_USER: root
      DW_DB_PASSWORD: root
      DW_DB_HOST: 172.31.43.141
      DW_DB_PORT: 3336
      ZK_PORT_2888_TCP_ADDR: z01.istresearch.com:2181
      KAFKA_PORT_9092_TCP_ADDR: 54.152.161.20
  volumes:
    - ../memex-datawake-stream:/memex-datawake-stream
    - ../dev-env:/dev-env
  command:
    - /memex-datawake-stream/dev_container_start.sh


dwsearch:
  build: ../trail-specific-search
  working_dir: /trail-specific-search
  links:
    - mysql:mysql
  environment:
    DW_DB_USER: root
    DW_DB_PASSWORD: root
    DW_DB_JDBC: jdbc:mysql://172.31.43.141:3336/datawake_prefetch
    DW_CRAWLER_TOPIC: memex.crawled_trail-entities-search
    DW_BING_KEY: AeLgwrJ49hIsdsivwmnGs6VOHq3cNs3vkKdnkYlwffQ
    DW_GOOGLE_PUBLIC_KEY: AIzaSyAdmOWQGKH38VkGRiprHtSIVP3NhbDj69A
    DW_GOOGLE_CUSTOM_SEARCH_CX: 017987995273492241149:qjaqo2emn3w
    DW_KAFKA_BROKERS: k01.istresearch.com:9092
    DW_USE_DISTRIBUTED: true
    DW_INCOMING_URLS: memex.incoming_urls
    DW_KAFKA_CRAWLER_BROKERS: k01.istresearch.com:9092
    DW_ZK_QUORUM: z01.istresearch.com:2181
    DW_SEARCH_API: http://54.69.102.155:8787/search/
  volumes:
    - ../trail-specific-search:/tss
  command: scala -classpath "build/libs/Search-Crawler-1.0-all.jar" com.soteradefense.datawake.trails.topology.search.SearchTopology


dwurlcontents:
  build: ../trail-specific-search
  working_dir: /trail-specific-search
  links:
    - mysql:mysql
  environment:
    DW_DB_JDBC: jdbc:mysql://172.31.43.141:3336/datawake_prefetch
    DW_CRAWLER_OUT: datawake-crawler-out
    DW_USE_DISTRIBUTED: true
    DW_KAFKA_BROKERS: k01.istresearch.com:9092
    DW_LOCAL_ZK_QUORUM: z01.istresearch.com:2181
    DW_ZK_QUORUM: z01.istresearch.com:2181
    DW_DB_USER: root
    DW_DB_PASSWORD: root
    DW_CRAWLER_TOPIC: memex.crawled_trail-entities-search
  command: scala -classpath "build/libs/Search-Crawler-1.0-all.jar" com.soteradefense.datawake.trails.topology.save.UrlContentsTopology


dwurlrank:
  build: ../trail-specific-search
  working_dir: /trail-specific-search
  links:
    - mysql:mysql
  environment:
      DW_DB_USER: root
      DW_DB_PASSWORD: root
      DW_DB_JDBC: jdbc:mysql://172.31.43.141:3336/datawake_prefetch
      DW_KAFKA_BROKERS: k01.istresearch.com:9092
      DW_ZK_QUORUM: z01.istresearch.com:2181
  command: scala -classpath "build/libs/Search-Crawler-1.0-all.jar" com.soteradefense.datawake.trails.topology.rank.UrlRankTopology


datawake:
  build: ../server
  links:
    - mysql:mysql
    - dwsearch
    - dwurlcontents
    - dwstream
    - dwurlrank
  ports:
    - "80:80"
  environment:
    DW_DB: datawake_prefetch
    DW_DB_USER: root
    DW_DB_PASSWORD: root
    DW_DB_HOST: 172.31.43.141
    DW_DB_PORT: 3336
    DW_KAFKA_CONN_POOL: k01.istresearch.com:9092
    DW_KAFKA_PUB_TOPIC: datawake-visited
    DW_KAFKA_TRAIL_TOPIC: datawake-trail-search
    DW_GOOGLE_CLIENT_IDS: 587886725690-bsns7flvb68l48q95f9l1su82q0p4k00.apps.googleusercontent.com,587886725690-njd26v0l3krmar5vtc8e06oprtqvkdvd.apps.googleusercontent.com
    DW_MOCK_AUTH:  1
    DW_CONN_TYPE: mysql
    PYTHONPATH: /usr/local/share/tangelo/web
  volumes:
    - ../server/:/usr/local/share/tangelo/web
    - ../server/conf/:/usr/local/share/tangelo/conf
  command: tangelo -c "/usr/local/share/tangelo/conf/tangelo.conf"
